import type { Metadata } from "next";
import LegalPageLayout, { type LegalSection } from "@/components/LegalPageLayout";

export const metadata: Metadata = {
    title: "Terms of Service — Senz8 Aroma",
    description:
        "Terms and conditions governing your use of senz8.in — operated by Senz8 Aroma Private Limited, Bangalore.",
    alternates: { canonical: "https://www.senz8.in/terms" },
    robots: { index: false, follow: false },
};

const sections: LegalSection[] = [
    {
        heading: "Introduction",
        body: (
            <>
                <p>This document is an electronic record generated by a computer system and does not require any physical or digital signature. It is published in accordance with applicable electronic record and intermediary guideline regulations, setting out the rules, regulations, and Terms of Use governing access to and usage of the SENZ8 website, including any related mobile site or mobile application (the &quot;Platform&quot;).</p>
                <p className="mt-4">The Platform is owned and operated by Senz8 Aroma Private Limited (&quot;SENZ8&quot;, the &quot;Platform Owner&quot;). Your use of the Platform, its services, and its tools is governed by these Terms of Use, together with the applicable policies incorporated herein by reference. If you transact on the Platform, you shall also be subject to the policies applicable to such transactions. By mere use of the Platform, you are contracting with SENZ8, and these Terms of Use, including all incorporated policies, constitute your binding obligations.</p>
                <p className="mt-4">Any additional or conflicting terms proposed by you are expressly rejected and shall be of no force or effect. These Terms of Use may be modified at any time without prior notice, and it is your responsibility to periodically review this page to stay informed of updates. For the purpose of these Terms, &quot;you&quot; or &quot;user&quot; means any natural or legal person who has agreed to become a user or buyer on the Platform.</p>
                <p className="mt-4 font-medium">By accessing, browsing, or otherwise using the Platform, you indicate your agreement to all the terms and conditions under these Terms of Use. Please read them carefully before proceeding.</p>
            </>
        ),
    },
    {
        heading: "Eligibility & Registration",
        body: (
            <p>To access and use our Services, you agree to provide true, accurate, and complete information during and after registration. You are responsible for all activity carried out through the use of your registered account.</p>
        ),
    },
    {
        heading: "Accuracy of Information",
        body: (
            <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials on this Platform. You acknowledge that such information may contain inaccuracies or errors, and we exclude liability for such inaccuracies to the fullest extent permitted by law.</p>
        ),
    },
    {
        heading: "Use of Services",
        body: (
            <p>Your use of our Services and the Platform is solely at your own risk. You must independently assess and ensure that our Services meet your requirements before relying on them.</p>
        ),
    },
    {
        heading: "Intellectual Property",
        body: (
            <p>The contents of the Platform — including but not limited to its design, layout, graphics, text, and any related branding — are proprietary to SENZ8. You do not acquire any rights to our intellectual property through your use of the Platform, and no content may be reproduced, distributed, modified, or used for commercial purposes without our prior written consent.</p>
        ),
    },
    {
        heading: "Prohibited Use",
        body: (
            <p>You agree not to use the Platform or our Services for any unlawful purpose or in violation of applicable Indian or local laws.</p>
        ),
    },
    {
        heading: "Links to Third Parties",
        body: (
            <p>The Platform may contain links to third-party websites or services that are not owned or controlled by SENZ8. Accessing these links will be governed by the terms of use and privacy policies of those third parties, and we accept no responsibility for their content, accuracy, or practices.</p>
        ),
    },
    {
        heading: "Legal Relationship",
        body: (
            <p>Initiating a transaction on our Platform constitutes a legally binding contract between you and SENZ8.</p>
        ),
    },
    {
        heading: "Indemnity",
        body: (
            <p>You agree to indemnify and hold harmless SENZ8, its affiliates, and its employees against any claims, damages, losses, or penalties arising out of your breach of these Terms.</p>
        ),
    },
    {
        heading: "Limitation of Liability",
        body: (
            <p>In no event will SENZ8 be liable for indirect, incidental, or consequential damages arising from your use of the Platform or our Services. Our total liability shall not exceed the amount paid by you for the specific product or service giving rise to the claim, or INR 100, whichever is less.</p>
        ),
    },
    {
        heading: "Force Majeure",
        body: (
            <p>SENZ8 shall not be liable for any failure or delay in performing its obligations under these Terms where such failure or delay results from events beyond our reasonable control.</p>
        ),
    },
    {
        heading: "Governing Law & Jurisdiction",
        body: (
            <p>These Terms shall be governed by and construed in accordance with the laws of India. All disputes arising from or relating to these Terms shall be subject to the exclusive jurisdiction of the courts of Bangalore, Karnataka.</p>
        ),
    },
    {
        heading: "Communication",
        body: (
            <p>All concerns or communications relating to these Terms must be directed to the contact details provided below.</p>
        ),
    },
    {
        heading: "Company Details",
        body: (
            <ul className="list-none flex flex-col gap-2 mt-1">
                {[
                    { label: "Domain Name (Website)", value: "senz8.in" },
                    { label: "Company Name (Platform Owner)", value: "Senz8 Aroma Private Limited" },
                    { label: "Registered Office Address", value: "No. 427 Srinivasa Nilaya, 6th Cross, Domlur, Bangalore North, Bangalore – 560071, Karnataka" },
                    { label: "City & State (Jurisdiction)", value: "Bangalore, Karnataka" },
                ].map((item, i) => (
                    <li key={i} className="flex items-start gap-3">
                        <span className="mt-1.5 w-1 h-1 rounded-full flex-shrink-0" style={{ background: "var(--accent-gold)" }} />
                        <span>
                            <span className="font-medium">{item.label}:</span> {item.value}
                        </span>
                    </li>
                ))}
            </ul>
        ),
    },
    {
        heading: "Contact",
        body: (
            <p>For any questions, concerns, or communications regarding these Terms of Service, please contact us at <span style={{ color: "var(--accent-gold)" }}>contact@senz8.in</span> or visit our <a href="/contact" style={{ color: "var(--accent-gold)", textDecoration: "underline", textDecorationColor: "rgba(212,175,55,0.3)" }}>Contact page</a>.</p>
        ),
    },
];

export default function TermsPage() {
    return (
        <LegalPageLayout
            badge="Legal"
            title={["Terms of", "Service."]}
            subtitle="Please read these terms carefully before using our website or placing an order."
            lastUpdated="July 2026"
            sections={sections}
        />
    );
}